include analytic module
pyfar/pyrato pull request #27
Opened 2024-08-12 12:42 UTC by hoyer-a

Include analytic module.

closes #26 

I had to make some changes to have the docs build succeed. 

Similar problems with auto-numbered footnotes as in https://github.com/pyfar/spharpy/pull/74. Seems like sphinx doesn't like it when auto-numbered footnotes appear twice (in the short function summary at the top and in the detailed function documentation).

2024-08-12 12:58 UTC, ahms5 requested changes
Thanks for taking care of it. It looks fine, I'm just wondering about the autonumbreing of the references.

2024-08-12 12:58 UTC, ahms5 commented on pyrato/analytic/analytic.py
> +    walls [1]_.
```suggestion
    walls [#]_.
```
doesn't auto numbering work?

2024-08-12 12:58 UTC, ahms5 commented on pyrato/analytic/analytic.py
> +    .. [3] H. Kuttruff, Room acoustics, pp. 64-66, 4th Ed. Taylor & Francis,
see above

2024-08-12 13:08 UTC, hoyer-a commented on pyrato/analytic/analytic.py
> +    walls [1]_.
This produces the "Too many autonumbered footnote references" error. Would have to restructure the docstring a bit to make it work.

 Maybe a general revision of the pyrato docs in a separate PR would make sense.

2024-08-12 13:14 UTC, ahms5 approved these changes

2024-08-16 07:41 UTC, mberz requested changes
I've marked a couple of functions to be removed from the init file, since they're intended for internal use only.
I guess this will reduce the problems with sphinx a bit as well.

2024-08-16 07:41 UTC, mberz commented on pyrato/analytic/__init__.py
> +    rectangular_room_impedance,
```suggestion
    eigenfrequencies_rectangular_room_impedance,
    rectangular_room_impedance,
```

2024-08-16 07:41 UTC, mberz commented on pyrato/analytic/__init__.py
> +    rectangular_room_impedance,
Most of these functions are intended for internal use only

2024-08-16 07:41 UTC, mberz commented on pyrato/analytic/__init__.py
> +    'rectangular_room_impedance',
```suggestion
    'eigenfrequencies_rectangular_room_impedance',
    'rectangular_room_impedance',
```
Same as above

2024-08-16 08:54 UTC, mberz approved these changes
Looks good, can be merged after #30 has been adapted and merged.

2024-08-16 11:22 UTC, merged