apply cookiecutter
pyfar/pyrato pull request #30
Opened 2024-08-12 13:40 UTC by ahms5

apply cookiecutter to upgrade the doc
related to #29

2024-08-12 13:42 UTC, ahms5 commented on setup.cfg
> +current_version = 0.1.0
```suggestion
current_version = 0.4.0
```

2024-08-12 13:43 UTC, ahms5 commented on .circleci/config.yml
> +   #        command: sudo apt-get update && sudo apt-get install -y libsndfile1 texlive-latex-extra dvipng
- run:
          name: Install System Dependencies
          command: sudo apt-get update && sudo apt-get install -y libsndfile1
```suggestion
   #    - run:
   #        name: Install System Dependencies
   #        command: sudo apt-get update && sudo apt-get install -y libsndfile1 texlive-latex-extra dvipng
```

2024-08-12 13:43 UTC, ahms5 commented on .circleci/config.yml
> +    #       command: sudo apt-get update && sudo apt-get install -y libsndfile1
```suggestion
      - run:
          name: Install System Dependencies
          command: sudo apt-get update && sudo apt-get install -y libsndfile1
```

2024-08-12 13:44 UTC, ahms5 commented on .readthedocs.yml
> +  #   - libsndfile1
```suggestion
  apt_packages:
    - libsndfile1
```

2024-08-12 13:45 UTC, ahms5 commented on README.rst
> +    :target: https://pyrato.readthedocs.io/en/latest/?badge=latest
```suggestion
.. image:: https://readthedocs.org/projects/pyrato/badge/?version=stable
    :target: https://pyrato.readthedocs.io/en/stable/?badge=stable
```

2024-08-12 15:25 UTC, mberz requested changes

2024-08-12 15:25 UTC, mberz commented on README.rst
> +`pyfar documentation`_ gives a detailed and complete overview of pyfar. All
This should link to the parato docs

2024-08-12 15:25 UTC, mberz commented on README.rst
> +.. _pyfar documentation: https://pyfar.readthedocs.io
This should link to the Pyrato docs

2024-08-13 06:26 UTC, hoyer-a reviewed
Thanks

2024-08-13 06:26 UTC, hoyer-a commented on pyrato/edc.py
> +    and the correction for the truncation is applied [#]_, [#]_, [#]_
```suggestion
    and the correction for the truncation is applied [#]_, [#]_, [#]_.
```

2024-08-13 06:55 UTC, hoyer-a approved these changes

2024-08-16 08:55 UTC, mberz reviewed
There have been changes in #27, please merge and check if this PR is affected.

2024-08-16 10:00 UTC, ahms5 commented
#27 is already merged into this one. and is the base for this pr.

2024-08-16 10:56 UTC, mberz commented
c30621e03fbd57ebdaa6648a75a2813f08b54c83

2024-08-16 10:58 UTC, ahms5 commented
done

2024-08-16 11:05 UTC, merged