apply cookiecutter
pyfar/pyrato pull request #36
Opened 2024-12-12 09:56 UTC by ahms5

2025-01-08 15:01 UTC, mberz approved these changes

2025-01-08 15:03 UTC, mberz requested changes
Apart from the deleted notebook all good

2025-01-08 15:03 UTC, mberz commented on examples/energy_decay_curves_and_reverberation_time.ipynb
Please revert deleting this notebook. It's not part of the gallery yet.

2025-04-23 18:38 UTC, ahms5 commented
on hold due to #48

2025-05-26 21:35 UTC, ahms5 commented
replaced by #48

2025-05-26 21:35 UTC, closed without merging