Restructure package
pyfar/pyrato pull request #43
Opened 2024-12-23 17:18 UTC by mberz

- [x] Do not import content of each sub-module to top level
- [x] Rename sub-modules if required

Tests will be adapted as soon as the import structure is finalized. 
Functions which have pyfar contour parts already will be replaced in separate PRs

2025-01-13 17:09 UTC, ahms5 commented on pyrato/__init__.py
>      'energy_decay_curve_analytic',
```suggestion
```
we dont need it here, don't we?

2025-01-13 17:18 UTC, ahms5 commented on pyrato/parametric.py
> -def reverberation_time_energy_decay_curve(
removing deprecations? wrong pr? 🍺 ?

2025-01-13 17:43 UTC, mberz commented on pyrato/parametric.py
> -def reverberation_time_energy_decay_curve(
The function had to go because it was much more elegant to simply rename the file 🤣

2025-01-13 17:50 UTC, mberz commented
> Thank you!
> 
> In pyfar we have a folder for each submodule, with a init as well. In this way it's easier to manage what is public, and what not, and whats part of the doc and what not. I would suggest to shift the submodules, into folders with an Init defining which method should be used and which not (e.g. private helpers).

I would not do this before agreeing on the new import structure.

2025-02-03 19:04 UTC, HenningSchaar approved these changes

2025-02-07 14:58 UTC, sikersten commented
- What about giving rap.py a descriptive name?
- Is it intended that docs are not built correctly, yet?

2025-02-07 15:18 UTC, mberz commented
> * What about giving rap.py a descriptive name?
Any suggestions?

> * Is it intended that docs are not built correctly, yet?
Yes, docs and tests need to be adjusted

2025-02-08 09:57 UTC, f-brinkmann commented
> What about giving rap.py a descriptive name?
>> Any suggestions?
How about 'parameters'?

What is the idea for later having convenience functions for that, which will wrap truncation, filtering, edc computation and analysis. Would they go in an extra module?

2025-02-11 15:22 UTC, ahms5 requested changes

2025-02-11 15:22 UTC, ahms5 commented on pyrato/__init__.py
> +from . import parametric
```suggestion
```
it its v1.0.0 we can remove the parametric at all, all will move to pyfar

2025-02-11 15:22 UTC, ahms5 commented on pyrato/__init__.py
> +    'air_attenuation_coefficient'
```suggestion
```
same here, all pyfar

2025-02-11 15:22 UTC, ahms5 commented on pyrato/__init__.py
>  )
```suggestion
```

how about the air attenuation? Maybe we can remove it since it will be part of the next pyfar release https://github.com/pyfar/pyfar/pull/734, and this is a pr for v1.0.0, isnt it?

maybe we can change ``energy_decay_curve_analytic`` in a way that it just uses air_attenuation_factor as input (remove frequency, air_absorption). then the calculation is upto the user

2025-02-11 15:22 UTC, ahms5 commented on pyrato/parametric.py
> +"""Parametric room acoustics calculations using simple geometric considerations
then this file can be removed

2025-02-11 15:22 UTC, ahms5 commented on pyrato/parametric.py
> +
```suggestion
```

this then belongs in a pr merging into ``main``/``develop`` and not into ``develop_v1.0.0``

2025-02-11 15:22 UTC, ahms5 commented on pyrato/rap.py
> +simulated or experimental data.
data or (room) impulse responses?

2025-02-11 15:27 UTC, ahms5 requested changes
and we need to merge dev_v1.0.0 again, since there where changes on main, which were not merged into dev

2025-02-12 17:50 UTC, mberz commented on pyrato/__init__.py
> +from . import parametric
I've not removed it since it can contain parametric room acoustic equations such as RT prediction using sabine's equation. The rest can indeed be imported from pyfar once released.

2025-02-12 17:50 UTC, mberz commented on pyrato/__init__.py
> +    'air_attenuation_coefficient'
See comment above, will remove once it's part of a new pyfar release.

2025-02-12 17:51 UTC, mberz commented on pyrato/parametric.py
> +
No, this is just so we don't forget to change it. ;)

2025-02-12 17:53 UTC, mberz commented on pyrato/rap.py
> +simulated or experimental data.
Currently it's based on EDCs only, but for others it might be RIRs as well. So It think data is fitting here.

2025-02-12 17:55 UTC, mberz commented
> > What about giving rap.py a descriptive name?
> > > Any suggestions?
> > > How about 'parameters'?
> 
> What is the idea for later having convenience functions for that, which will wrap truncation, filtering, edc computation and analysis. Would they go in an extra module?

I would argue that parameters is even less descriptive than (r)oom (a)coustic (p)arameters ;)
I'm not sure about the convenience functions. I have nothing against placing them in here as well, seems like a fitting place.

2025-02-13 07:06 UTC, f-brinkmann commented
I'm fine with both names, rap and paramters.

2025-02-13 18:40 UTC, mberz commented on pyrato/parametric.py
> +"""Parametric room acoustics calculations using simple geometric considerations
See above, this file will contain things like Sabine's eq. etc.

2025-02-13 18:42 UTC, mberz commented
> and we need to merge dev_v1.0.0 again, since there where changes on main, which were not merged into dev

done

2025-02-14 15:42 UTC, merged